# Generated by Django 5.2.12 on 2026-03-24 12:40

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('memories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MemoryDetail',
            fields=[
                ('memory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='memories.memory')),
                ('content', models.TextField()),
                ('content_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
            ],
            options={
                'db_table': 'memory_details',
            },
        ),
        migrations.AddField(
            model_name='memory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='memories.category'),
        ),
        migrations.AddField(
            model_name='memory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memories', to='locations.location'),
        ),
        migrations.AddField(
            model_name='memory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoryimage',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='memories.memory'),
        ),
        migrations.AddField(
            model_name='tag',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='memories.memory'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('memory', 'name'), name='unique_memory_tag'),
        ),
    ]
