# Generated by Django 5.2.6 on 2026-03-29 13:07

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorydetail',
            name='content_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
