# Generated by Django 5.2.6 on 2026-04-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_change_embedding_dim_3072'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoryimage',
            name='storage_url',
        ),
        migrations.AddField(
            model_name='memoryimage',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='memory_images/%Y/%m/'),
        ),
    ]
