# Generated by Django 5.2.6 on 2026-04-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_remove_memoryimage_storage_url_memoryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memory_images/%Y/%m/'),
        ),
    ]
