# Generated by Django 5.2.12 on 2026-05-12 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('locations', '0001_initial'),
        ('memories', '0006_alter_memoryimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='author_nickname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='memory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='groups.group'),
        ),
        migrations.AddField(
            model_name='memory',
            name='group_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='groups.groupcategory'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['group', '-visited_at'], name='idx_memories_group_date'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'group'], name='idx_memories_user_group'),
        ),
        migrations.AddConstraint(
            model_name='memory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('group_category__isnull', True)), models.Q(('category__isnull', True), ('group__isnull', False)), _connector='OR'), name='chk_category_scope'),
        ),
    ]
