# Generated by Django 5.2.12 on 2026-05-12 15:33

import django.db.models.deletion
import groups.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_img_url', models.TextField(blank=True, null=True)),
                ('invite_code', models.CharField(default=groups.models._default_invite_code, max_length=20, unique=True)),
                ('max_members', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('member_joined', '멤버 가입'), ('member_left', '멤버 탈퇴'), ('member_banned', '멤버 추방'), ('member_role_changed', '역할 변경'), ('memory_created', '기억 생성'), ('memory_deleted', '기억 삭제'), ('group_updated', '그룹 수정'), ('invite_code_reset', '초대 코드 재발급')], max_length=30)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_activities', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='groups.group')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_activity_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', '-created_at'], name='idx_activity_group_recent')],
            },
        ),
        migrations.CreateModel(
            name='GroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color_code', models.CharField(default='#007AFF', max_length=7)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='group_categories_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='groups.group')),
            ],
            options={
                'db_table': 'group_categories',
                'constraints': [models.UniqueConstraint(fields=('group', 'name'), name='unique_group_category')],
            },
        ),
        migrations.CreateModel(
            name='GroupChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('ai_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_chat_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', '-created_at'], name='idx_group_chat_recent')],
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('token', models.CharField(default=groups.models._default_token, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('owner', '오너'), ('admin', '관리자'), ('member', '멤버'), ('viewer', '뷰어')], default='member', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='groups.group')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_invitations',
                'indexes': [models.Index(fields=['expires_at'], name='idx_invitation_expires'), models.Index(fields=['group', 'email'], name='idx_invitation_group_email')],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', '오너'), ('admin', '관리자'), ('member', '멤버'), ('viewer', '뷰어')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('pending', '대기'), ('active', '활성'), ('left', '탈퇴'), ('banned', '추방')], default='pending', max_length=10)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_members',
                'indexes': [models.Index(fields=['user', 'status'], name='idx_member_user_status'), models.Index(fields=['group', 'status'], name='idx_member_group_status')],
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='unique_group_member')],
            },
        ),
    ]
