# Generated by Django 5.2.12 on 2026-03-24 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('province', models.CharField(help_text='시/도 (ex: 서울특별시)', max_length=50)),
                ('city_district', models.CharField(help_text='시/군/구 (ex: 강남구)', max_length=50)),
                ('town_neighborhood', models.CharField(help_text='법정동/리 (ex: 역삼동)', max_length=50)),
                ('admin_town', models.CharField(blank=True, help_text='행정동 (ex: 역삼1동)', max_length=50, null=True)),
            ],
            options={
                'db_table': 'address_regions',
                'constraints': [models.UniqueConstraint(fields=('province', 'city_district', 'town_neighborhood'), name='unique_region_idx')],
            },
        ),
        migrations.CreateModel(
            name='AddressDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('road_address_name', models.TextField(blank=True, help_text='도로명 주소 전체 (ex: 테헤란로 212)', null=True)),
                ('address_name', models.TextField(blank=True, help_text='지번 주소 전체 (ex: 역삼동 642-1)', null=True)),
                ('main_address_no', models.CharField(blank=True, help_text='본번 (ex: 642)', max_length=20, null=True)),
                ('sub_address_no', models.CharField(blank=True, help_text='부번 (ex: 1)', max_length=20, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_details', to='locations.addressregion')),
            ],
            options={
                'db_table': 'address_details',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kakao_place_id', models.CharField(blank=True, help_text='카카오 맵 고유 ID (지도 직접 클릭 시 null)', max_length=50, null=True, unique=True)),
                ('place_name', models.CharField(help_text='장소명 (ex: 멀티캠퍼스 역삼)', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='locations.addressdetail')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.AddConstraint(
            model_name='addressdetail',
            constraint=models.UniqueConstraint(fields=('region', 'road_address_name', 'address_name', 'main_address_no', 'sub_address_no'), name='unique_detail_address_idx'),
        ),
    ]
